sudo: required
services:
  - docker

before_install:
  - docker build -t oabai/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true oabai/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app:  Docker-react
  env: DockerReact-env
  bucket-name: "elasticbeanstalk-us-east-2-223770893546"
  bucket-path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
